### PR TITLE
Fix trailing space in java version

### LINKED ISSUE #22: JAVA_HOME not found
Related to #3 and/or #20.

I installed Java (open JDK 11) and Maven 3.6.0 using asdf on Ubuntu 18.10. I am using bash for this.

I added a call to the java wrapper in my `.bashrc.`:
```
. $HOME/.asdf/plugins/java/asdf-java-wrapper.bash
```
When I open a shell, and execute `echo $JAVA_HOME` the output is correct and shows the asdf install dir of the JDK. 

```
~$ echo $JAVA_HOME
/home/henry/.asdf/installs/java/openjdk-11.0.1
```

But when I run Maven it somehow loses the value of JAVA_HOME and shows:

```
~$ mvn
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
```

### PR DESCRIPTION
**Pull request by jvassev**
Fixes #22

### CODE REVIEW

**Comment by nderraugh** [comment]
lgtm

**Comment by mcountis** [comment]
👍 works in my env.

**Comment by honsq90** [comment]
when will this be merged? just to help with future installs. (I've just fixed it locally which is fine)

**Comment by flaprano** [comment]
same problem here and where resolved fixing locally.

**Comment by mattysweeps** [comment]
This still needs to be merged

**Pull request merged**
