### PR TITLE
#3 Use asdf-provided java (if available)

### LINKED ISSUE #3: Maven should use asdf provided java somehow
Instead it always falls back to the system one.

See https://github.com/skotchpine/asdf-java/issues/5 for explanation. Maybe we can solve it here?

### PR DESCRIPTION
**Pull request by unicolet**
Fixes #3 

@skotchpine wdyt?

### CODE REVIEW

**Comment by skotchpine** [comment]
I didn't mind the comment, though I also like the echo. Just curious, why `_JAVA_HOME` rather than `java_home`?

**Comment by unicolet** [comment]
@skotchpine it's `_JAVA_VERSION` with the leading underscore, not `JAVA_HOME` ;-)

I dropped the comment because it would be surprising for somebody relying on "standard" mvn output to parse it :-)

**Comment by unicolet** [comment]
@skotchpine the `_` prefix is just to avoid polluting the env, JAVA_VERSION just seems a too popular name for a temp var. I can make it lowercase, shall I?

**Comment by skotchpine** [comment]
Okay, cool. Please do. I prefer lowercase unless exporting.

**Comment by unicolet** [comment]
@skotchpine done, thanks :-)

**Comment by skotchpine** [comment]
No no, thank you for the commitment. I may be going overboard some

**Pull request merged**
